#!/usr/bin/env bash
#echo 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7-dmr' | su#do tee -a /etc/apt/sources.list
#sudo apt-get update
#sudo apt-get install mysql-server-5.7
#sudo apt-get install python3-dev
#sudo apt-get install libmysqlclient-dev
#sudo apt-get install zlib1g-dev
#sudo pip3 install mysqlclient==1.3.10
sudo pip3 install SQLAlchemy==1.2.5
